[manager]
prepend_keymap = [
  {on = "!", run = "shell '~/.config/yazi/kitty.sh $0' --confirm"},
  {on = "<C-o>", run = "shell '~/.config/yazi/default_app_chooser.sh $*' --confirm"},
  {on = "e", run = "shell ' $*' --cursor=0 --interactive"},
  {on = "<Enter>", run = "plugin --sync smart-enter"},
]
[input]
prepend_keymap = [
  {on = "<Esc>", run = "close", desc = "Cancel input"}
]
