[manager]

show_hidden = true
linemode = "size"

[opener]

open = [
  { run = 'xdg-open "$@"', desc = "Open"},
  { run = 'eog $@'},
]

edit = [
  { run = 'nvim "$@"', block = true },
  { run = 'code "$@"'},
]

[open]
