[manager]

show_hidden = true
linemode = "size"

[opener]

open = [
  { run = 'xdg-open "$@"', orphan = true, desc = "Open"},
]

edit = [
  { run = 'nvim "$@"', block = true },
  { run = 'code "$@"'},
]

[open]
