export PATH="$PATH:$HOME/.fvm_flutter/bin"
export PATH="$PATH:$HOME/.spicetify"
export PATH="$PATH:$HOME/.pub-cache/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:/home/lifisage/.local/bin"
